/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_CX2KlKFnR",
    "aws_user_pools_web_client_id": "2fo3niq75q7supd52fqpir88lj",
    "oauth": {}
};


export default awsmobile;
