/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:3c5ac08b-23ce-4a09-9ef2-afec4895fe00",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_PqeXJO0WO",
    "aws_user_pools_web_client_id": "2c6tq1f429mqtp63d05b11ma67",
    "oauth": {}
};


export default awsmobile;
